// 简体中文模板

export default {
  moldName: "default",
  fonts: {
    "cn-simplify": {
      name: "cn_simplify.ttf",
      type: "relative",
    },
    number: {
      name: "number.ttf",
      type: "relative",
    },
    link: {
      name: "link.ttf",
      type: "relative",
    },
    password: {
      name: "password.ttf",
      type: "relative",
    },
  },
  style: {
    moldSize: [813, 1185],
    name: {
      font: "cn-simplify",
      fontSize: 65,
      maxWidth: 610,
      position: [65, 96],
    },
    pic: {
      position: [101, 220, 614, 616],
      position_lb: [57, 213, 702, 528],
    },
    attribute: {
      position: [680, 57, 75, 75],
      size: [66, 66],
    },
    level: {
      position: [686, 145],
      size: [50, 50],
      distance: 55,
    },
    monsterDesc: {
      splitMode: "cn",
      font: "cn-simplify",
      fontSize: 24,
      lbFontSize: 22,
      position: [66, 942],
      lbPosition: [130, 773],
      lineHeight: 26,
      lbLineHeight: 24.5,
      maxLines: 6,
      maxWidth: 683,
    },
    spellDesc: {
      splitMode: "cn",
      font: "cn-simplify",
      fontSize: 24,
      position: [66, 915],
      lineHeight: 24,
      maxLines: 9,
      maxWidth: 683,
    },
    race: {
      font: "cn-simplify",
      fontSize: 26,
      position: [53, 915],
      maxWidth: 610,
    },
    type: {
      font: "cn-simplify",
      fontSize: 48,
      position: [750, 185],
      icon: [667, 147],
      iconSize: [46, 46],
    },
    ATK: {
      font: "number",
      fontSize: 36,
      position: [585, 1107],
    },
    DEF: {
      font: "link",
      fontSize: 36,
      position: [750, 1107],
    },
    pendulumNumber: {
      font: "number",
      fontSize: 52,
      positonLeft: [88, 854],
      positonRight: [730, 854],
    },
    linkArrows: {
      center: [408, 528],
      arrow1: {
        size: [140, 41],
        position: [-70, 308],
      },
      arrow2: {
        size: [70, 70],
        position: [-336, 267],
      },
    },
    cardbag: {
      font: "password",
      fontSize: 24,
      position: [728, 871],
      linkPosition: [665, 872],
      pendulumPosition: [66, 1104],
    },
    password: {
      font: "password",
      fontSize: 23,
      position: [40, 1149],
    },
    holo: {
      position: [743, 1115],
      size: [42, 42],
    },
  },
  translate: {
    attribute: {
      light: "光",
      dark: "暗",
      wind: "风",
      water: "水",
      fire: "炎",
      earth: "地",
      divine: "神",
    },
    type: {
      tc: "通常",
      xg: "效果",
      ys: "仪式",
      rh: "融合",
      tk: "衍生物",
      tt: "同调",
      cl: "超量",
      lb: "灵摆",
      lj: "连接",
      ec: "二重",
      tz: "调整",
      tm: "同盟",
      kt: "卡通",
      lh: "灵魂",
      fz: "反转",
      ts: "特殊召唤",
      zb: "装备",
      sg: "速攻",
      cd: "场地",
      fj: "反击",
      yx: "永续",
    },
    raceList: [
      "龙族",
      "战士族",
      "恶魔族",
      "魔法师族",
      "天使族",
      "不死族",
      "岩石族",
      "植物族",
      "昆虫族",
      "水族",
      "炎族",
      "雷族",
      "魚族",
      "海龙族",
      "幻龙族",
      "恐龙族",
      "爬虫类族",
      "机械族",
      "兽族",
      "鸟兽族",
      "兽战士族",
      "念动力族",
      "电子界族",
      "幻神兽族",
      "创造神族",
    ],
    spell: "魔法卡",
    trap: "陷阱卡",
    brackets: ["【", "】"],
  },
};
