import commonStyle from './common.js';

export default {
  moldName: "default",
  fonts: {
    cn: {
      name: "cn.ttf",
      type: "relative",
    },
    number: {
      name: "number.ttf",
      type: "relative",
    },
    link: {
      name: "link.ttf",
      type: "relative",
    },
    password: {
      name: "password.ttf",
      type: "relative",
    },
  },
  style: Object.assign(JSON.parse(commonStyle), {
    fontMap: {
      name: "cn",
      desc: "cn",
      race: "cn",
      attack: "number",
      link: "link",
      password: "password",
      type: "cn",
      lbNum: "number",
      copyright: "微软雅黑,Sans",
    },
  }),
  translate: {
    attribute: {
      light: "光",
      dark: "暗",
      wind: "风",
      water: "水",
      fire: "炎",
      earth: "地",
      divine: "神",
    },
    type: {
      tc: "通常",
      xg: "效果",
      ys: "儀式",
      rh: "融合",
      tt: "同調",
      cl: "超量",
      lb: "靈擺",
      lj: "連接",
      ec: "二重",
      tz: "調整",
      tm: "同盟",
      kt: "卡通",
      lh: "靈魂",
      fz: "反轉",
      ts: "特殊召喚",
      zb: "裝備",
      sg: "速攻",
      cd: "場地",
      fj: "反擊",
      yx: "永續",
    },
    raceList: [
      "龍族",
      "戰士族",
      "惡魔族",
      "魔法師族",
      "天使族",
      "不死族",
      "岩石族",
      "植物族",
      "昆蟲族",
      "水族",
      "炎族",
      "雷族",
      "魚族",
      "海龍族",
      "幻龍族",
      "恐龍族",
      "爬蟲类族",
      "機械族",
      "獸族",
      "鳥獸族",
      "獸戰士族",
      "念動力族",
      "電子界族",
      "幻神獸族",
      "創造神族",
    ],
    spell: "魔法卡",
    trap: "陷阱卡",
    brackets: ["【", "】"],
  },
};
